# 第0节：NumPy简介
NumPy是一个开源的Python科学计算基础库，包含：
+ 一个强大的N维数组对象ndarray
+ 广播功能函数
+ 整合C/C++/Fortran代码的工具
+ 线性代数、傅里叶变换、随机数生成等功能

NumPy是SciPy、Pandas等数据处理或科学计算库的基础

---
**例1：计算$C = $$A^2$ + $B^3$，其中，A和B是一维数组**

a = [0, 1, 2, 3, 4]

b = [9, 8, 7, 6, 5]

c = [729, 513, 347, 225, 141]

In [105]:
#传统方法
def Pysum():
    a = [0, 1, 2, 3, 4]
    b = [9, 8, 7, 6, 5]
    c = []

    for i in range(len(a)):
        c.append(a[i]**2 + b[i]**3)
    return c

print("c = ",Pysum())

c =  [729, 513, 347, 225, 141]


In [106]:
#numpy方法
import numpy as np

def npSum():
    a = np.array([0, 1, 2, 3, 4])
    b = np.array([9, 8, 7, 6, 5])
    c = a**2 + b**3
    return c

print("c = ",npSum())

c =  [729 513 347 225 141]


-----
**使用numpy的优点**

+ 去掉元素间运算所需的循环，使一维向量更像单个数据

+ 设置专门的数组对象，经过优化，可以提升运算速度

**一般的：**科学计算中，一个维度所有数据的类型往往相同
+ 数组对象采用相同的数据类型，有助于节省运算和存储空间

**Tips：**numpy底层由C语言实现，运算速度是Python的**10倍**以上

---
**N维数组对象：ndarray**
+ 实际数据
+ 描述这些数据的元数据（数据维度、数据类型等）
+ 要求所有元素类型相同（同质），数组下标从0开始

In [107]:
import numpy as np

a = np.array([[0, 1, 2, 3, 4], [9, 8, 7, 6, 5]])

In [108]:
a #直接写上变量名，在命令行会直接显示变量信息

array([[0, 1, 2, 3, 4],
       [9, 8, 7, 6, 5]])

In [109]:
print(a) #注意 a 与 print(a)的区别

[[0 1 2 3 4]
 [9 8 7 6 5]]


---
# 第1节：ndarray基本概念**
1. 轴（axis）:数据维度
2. 秩（rank）:轴的数量

In [110]:
# ndarry的5个基本属性
import numpy as np

# 先创建一个ndarray
a = np.array([[0, 1, 2, 3, 4], [9, 8, 7, 6, 5]])

# .ndim：秩，即轴的数量(或维度的数量)
print("a.ndim = ", a.ndim)

# .shape：对象的尺度，对于矩阵，n行m列
print("a.shape = ", a.shape)

# .size：对象元素的个数(相当于.shape中n*m的值)
print("a.size = ", a.size)

# .dtype：对象的元素类型
print("a.dtype = ", a.dtype)

# .itemsize：对象中每个元素的大小，以字节为单位
print("a.itemsize = ", a.itemsize)

a.ndim =  2
a.shape =  (2, 5)
a.size =  10
a.dtype =  int32
a.itemsize =  4


---
### ndarray的元素类型（了解）
![avatar](./image/day1-img1.PNG)
![avatar](./image/day1-img2.PNG)
![avatar](./image/day1-img3.PNG)

In [111]:
# numpy支持非同质的元素类型，但是一般情况不要使用
import numpy as np

a = np.array([[0, 1, 2], [0, 1, 2, 3, 4]])

print("a.shape = ", a.shape)

print("a.size = ", a.size)

print("a.dtype = ", a.dtype)# 元素类型：object（对象）

print("a.itemsize = ", a.itemsize)

print("a.ndim = ", a.ndim)# 相当于一组对象，所以维度数量为1

a.shape =  (2,)
a.size =  2
a.dtype =  object
a.itemsize =  8
a.ndim =  1


---
# 第2节：ndarray的创建
+ 从Python中的列表、元组等类型创建
+ 使用NumPy中函数创建（如：arange, ones, zeros）
+ 从字节流（raw bytes）中创建（了解）
+ 从文件中读取特定格式创建（了解）

In [112]:
# 从Python中的列表、元组等类型创建
import numpy as np

List1 = [[1,2,3],[7,8,9]]
Tuple1 = (1,2,3,4,5)

# 从列表创建
a = np.array(List1,dtype = np.float32)
b = np.array(List1)

# 从元组创建
c = np.array(Tuple1)
d = np.array(Tuple1,dtype = np.float32)

In [113]:
# 注意看 a 和 b(c 和 d) 的差别（指定了 dtype 和没有指定的差别）
a,b,c,d

(array([[1., 2., 3.],
        [7., 8., 9.]], dtype=float32),
 array([[1, 2, 3],
        [7, 8, 9]]),
 array([1, 2, 3, 4, 5]),
 array([1., 2., 3., 4., 5.], dtype=float32))

In [114]:
import numpy as np
# 从 列表、元组混合 创建
T = [
    [1,2,3],
    [4,5],
    (9,8,7)
]
np.array(T)

array([list([1, 2, 3]), list([4, 5]), (9, 8, 7)], dtype=object)

**从NumPy函数创建（最常用）**


In [115]:
# np.arange(n)
# 返回数组[0,1,2,3,...,n-1]
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

---
**NumPy函数1**
+ np.ones(shape) 根据shape生成全 0 数组
+ np.zeros(shape) 根据shape生成全 1 数组
+ np.full(shape,val) 根据shape生成全 val 数组
---
**shape是元组，shape的含义**

例子：
+ 一维数组：shape=(5) => 长度为5的一维数组
+ 二维数组：shape=(3,4) => 3x4矩阵


In [116]:
b = np.ones((2,3))
c = np.zeros((2,3))
d = np.full((2,3),-1)
# 可以在后面指定 dtype 类型
# 例如：d = np.full((2,3),-1,dtype=np.float32)

b,c,d

(array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[0., 0., 0.],
        [0., 0., 0.]]),
 array([[-1, -1, -1],
        [-1, -1, -1]]))

---
**NumPy函数2**
+ np.ones_like(a) 根据数组a的形状生成一个全1数组
+ np.zeros_like(a) 根据数组a的形状生成一个全0数组
+ np.full_like(a,val) 根据数组a的形状生成一个数组，每个元素值都是val

In [117]:
a = [
    [1, 2],
    [3, 4]
]

b = np.ones_like(a)
c = np.zeros_like(a)
d = np.full_like(a, -2)
# 同样可以设置dtype
# d = np.full_like(a, -2,dtype=np.float32)

b,c,d

(array([[1, 1],
        [1, 1]]),
 array([[0, 0],
        [0, 0]]),
 array([[-2, -2],
        [-2, -2]]))

---
**NumPy函数3**
+ np.linspace() 根据起止数据等间距地填充数据，形成数组
+ np.concatenate() 将两个或多个数组合并成一个新的数组

In [118]:
# 区间[1,10]中,等距的取4个数
a = np.linspace(1, 10, 4)

# endpoint参数表示右区间是闭还是合
# endpoint = False => 区间为[1,10)
b = np.linspace(1, 10, 4, endpoint=False)

# 可指定 dtype
# a = np.linspace(1, 10, 4, dtype=np.int32)
# b = np.linspace(1, 10, 4, endpoint=False, dtype=np.int32)
a, b

(array([ 1.,  4.,  7., 10.]), array([1.  , 3.25, 5.5 , 7.75]))

In [119]:
# 将多个数组合并
a = [1,3,5]
b = [2,4,6,8]
c = [-1,-2,-3]
d = np.concatenate((a,b,c))
d

array([ 1,  3,  5,  2,  4,  6,  8, -1, -2, -3])

---
**ndarray数组的变换**
+ 改变元素类型直接设置dtype
+ 使用相关函数进行维度变换
---
+ .reshape(shape) 不改变数组元素，返回一个shape形状的数组，原数组不变
+ .resize(shape)与.reshape()功能一致，但修改原数组
+ .swapaxes(ax1,ax2) 将数组n个维度中两个维度进行调换
+ .flatten() 对数组进行降维，返回折叠后的一维数组，原数组不变

In [120]:
import numpy as np

# (1)不改变数组元素(2)原数组不变
# 返回一个shape形状的数组

a = np.array([1,2,3,4,5,6,7,8])
b = a.reshape((2,4))
a,b

(array([1, 2, 3, 4, 5, 6, 7, 8]),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]]))

In [121]:
# a.resize()作用跟a.reshape一致
# 但是改变原数组
a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [122]:
a.resize((2,4))
a
#可以看到a已经改变了

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [123]:
import numpy as np

# a.swapaxes(0,1)
# 将a的第 0 和第 1 维度进行调换
a = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

a,a.swapaxes(0,1)

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]]))

In [124]:
import numpy as np

a = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
# 将a降维为 1 维
a,a.flatten()

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([1, 2, 3, 4, 5, 6, 7, 8]))

In [125]:
# new_a = a.astype(new_type)
# 生成 a 的拷贝a'，把a’的元素全都修改成新的类型（显然a不变）
import numpy as np

a = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
b = a.astype(np.float32)
a,b #注意 a 是没有改变的

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[1., 2., 3., 4.],
        [5., 6., 7., 8.]], dtype=float32))

In [126]:
#ndarray转换为list
import numpy as np

a = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
a,a.tolist()


(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 [[1, 2, 3, 4], [5, 6, 7, 8]])

# 第3节：ndarray数组的操作
---

**索引**

arr = [9 , 3, 2, 5, 6]

id1 = [0 , 1, 2, 3, 4]（正索引）

id2 = [-5,-4,-3,-2,-1]（负索引）

In [127]:
# 索引复习
arr = [9,3,2,5,6]
print(arr[0],arr[-1])

9 6


In [128]:
# 切片复习
# 基本格式a[begin:end:step]
# 区间[begin,end)中，每隔step取一个元素
#--------------------------------------------#
# ：个数

In [129]:
# 0个：直接相当于索引
b = np.arange(8)
print(b,b[1])

# 1个：表示省略step，这时step默认1
print(b[1:3])

# 2个，这是最标准的写法
print(b[1:5:2])

[0 1 2 3 4 5 6 7] 1
[1 2]
[1 3]


In [130]:
# step：正表示“从左往右”取值，负表示“从右往左”取值。当step省略时，默认为1，即从左往右以步长1取值

# begin: 起始索引（包含该索引）
# 该参数省略时，表示从对象“端点”开始取值，至于是从“起点”还是从“终点”开始
# 则由step参数的正负决定，step为正从“起点”开始，为负从“终点”开始。

# end：终止索引（不包含该索引）
# 该参数省略时，表示一直取到数据“端点”，至于是到“起点”还是到“终点”
# 由step参数的正负决定，step为正时直到“终点”，为负时直到“起点”

# 具体参考这个链接
# https://www.jianshu.com/p/15715d6f4dad

---
**以上是一维数组的索引/切片复习**

下面来看下多维数组的情况

---

### 多维数组的索引

In [131]:
import numpy as np

a = np.arange(8).reshape(2, 4)
print(a)

# 每个维度一个索引值，逗号分割
# 把每一个维度都当作一维数组即可

print(a[1,2])
print(a[-1,-1])

[[0 1 2 3]
 [4 5 6 7]]
6
7


In [132]:
# 每个维度切片方法，与一维数组相同
import numpy as np

a = np.arange(8).reshape(2, 4)
print(a)

[[0 1 2 3]
 [4 5 6 7]]


In [133]:
#对于<某个维度>,没有:表示选取这个维度
a[1,1:3] 

array([5, 6])

In [134]:
#一个:表示选取本维度[begin,end)所有元素
a[:,1:3]

array([[1, 2],
       [5, 6]])

In [135]:
#2个: 表示添加步长step
a[:,::-1] 

array([[3, 2, 1, 0],
       [7, 6, 5, 4]])

---
# 第4节：ndarray数组的运算

数组与标量之间的运算：作用于数组的每一个元素

In [136]:
#例如:数组+5 => 数组内每一个元素都+5
import numpy as np

a = np.arange(8).reshape(2, 4)
print(a)
a += 5
print(a)

# a.mean()表示数组a的平均值
print(a.mean())

[[0 1 2 3]
 [4 5 6 7]]
[[ 5  6  7  8]
 [ 9 10 11 12]]
8.5


In [137]:
# numpy一元函数

# np.ceil(x) np.floor(x) 计算数组各元素的ceiling值 或 floor值
a = np.array([1.2,2.5,3.6])
# 向上取整/向下取整
print(np.ceil(a),np.floor(a))

[2. 3. 4.] [1. 2. 3.]


In [138]:
# np.rint(x) 计算数组各元素的四舍五入值
# np.modf(x) 将数组各元素的小数和整数部分以两个独立数组形式返回
a = np.array([1.2,2.5,3.6])
print(np.rint(a))
print(np.modf(a))

[1. 2. 4.]
(array([0.2, 0.5, 0.6]), array([1., 2., 3.]))


---
**常见一元函数举例**
![avatar](./image/day1-img4.PNG)
![avatar](./image/day1-img5.PNG)

In [139]:
# numpy二元函数
import numpy as np

a = [1, 4, 6]
b = [-1, 5, -3]
a, b = np.array(a), np.array(b)

np.maximum(a,b) #等价于np.fmax(a,b)
#np.mod(a,3)

array([1, 5, 6])

----
**常见二元函数举例**
![avatar](./image/day1-img6.PNG)